AWSTemplateFormatVersion: "2010-09-09"
Description: Edge Layer - Route53, CloudFront, S3, WAF and ACM

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name

  DomainName:
    Type: String
    Description: Base domain name (ex: seusite.com)

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID

  CertificateARN:
    Type: String
    Description: ACM Certificate ARN (must be in us-east-1)

  ALBDomainName:
    Type: String
    Description: DNS name of the public Application Load Balancer (Web Tier)

Resources:

  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: { Fn::Sub: "${ProjectName}-${Environment}-static-content" }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: { Fn::Sub: "${ProjectName}-${Environment}-static" }
        - Key: Environment
          Value: { Ref: Environment }

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: { Fn::Sub: "${ProjectName}-${Environment}-waf" }
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: { Fn::Sub: "${ProjectName}-${Environment}-waf" }
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRules

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        Aliases:
          - { Ref: DomainName }
        Origins:
          - Id: S3Origin
            DomainName: { Fn::GetAtt: [StaticContentBucket, RegionalDomainName] }
            S3OriginConfig: {}
          - Id: ALBOrigin
            DomainName: { Ref: ALBDomainName }
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: true
            Cookies: { Forward: all }
        CacheBehaviors:
          - PathPattern: "/static/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
              Cookies: { Forward: none }
        ViewerCertificate:
          AcmCertificateArn: { Ref: CertificateARN }
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        WebACLId: { Ref: WebACL }

  CloudFrontDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: { Ref: HostedZoneId }
      Name: { Ref: DomainName }
      Type: A
      AliasTarget:
        DNSName: { Fn::GetAtt: [CloudFrontDistribution, DomainName] }
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontDomainName:
    Value: { Fn::GetAtt: [CloudFrontDistribution, DomainName] }
  StaticBucketName:
    Value: { Ref: StaticContentBucket }