AWSTemplateFormatVersion: "2010-09-09"
Description: Auto Scaling Group for Web Tier

Parameters:
  Environment: { Type: String }
  ProjectName: { Type: String }
  VpcId: { Type: AWS::EC2::VPC::Id }
  PrivateWebSubnets: { Type: List<AWS::EC2::Subnet::Id> }
  WebTargetGroupArn: { Type: String }
  InstanceType: { Type: String }
  LatestAMIId: { Type: AWS::EC2::Image::Id }
  KeyName: { Type: AWS::EC2::KeyPair::KeyName }
  # Adicionado para resolver o erro de referência
  ALBWebSecurityGroupId: { Type: String }

Resources:
  WebInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic from ALB Web
      VpcId: { Ref: VpcId }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          # Usando o parâmetro correto com sintaxe completa
          SourceSecurityGroupId: { Ref: ALBWebSecurityGroupId }
      Tags:
        - Key: Name
          Value: { Fn::Sub: "${ProjectName}-${Environment}-web-sg" }

  WebLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: { Ref: LatestAMIId }
        InstanceType: { Ref: InstanceType }
        KeyName: { Ref: KeyName }
        SecurityGroupIds:
          - { Ref: WebInstanceSecurityGroup }
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl start httpd
              systemctl enable httpd
              echo "<h1>Web Tier - ${Environment}</h1>" > /var/www/html/index.html

  WebAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: { Ref: PrivateWebSubnets }
      LaunchTemplate:
        LaunchTemplateId: { Ref: WebLaunchTemplate }
        Version: { Fn::GetAtt: [WebLaunchTemplate, LatestVersionNumber] }
      MinSize: "2"
      MaxSize: "4"
      DesiredCapacity: "2"
      TargetGroupARNs:
        - { Ref: WebTargetGroupArn }
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

Outputs:
  WebSecurityGroupId:
    Value: { Ref: WebInstanceSecurityGroup }