AWSTemplateFormatVersion: "2010-09-09"
Description: Security Groups - ALB, Application and RDS

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:

  # =========================
  # ALB - Web Layer
  # =========================
  AlbWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Web SG
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # =========================
  # Application Layer
  # =========================
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Application SG
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId:
            Ref: AlbWebSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # =========================
  # Database Layer
  # =========================
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS PostgreSQL SG
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId:
            Ref: AppSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  AlbWebSecurityGroupId:
    Value:
      Ref: AlbWebSecurityGroup

  AppSecurityGroupId:
    Value:
      Ref: AppSecurityGroup

  RDSSecurityGroupId:
    Value:
      Ref: RDSSecurityGroup
