AWSTemplateFormatVersion: "2010-09-09"
Description: VPC with public and private subnets in two AZs

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  ########################
  # PUBLIC SUBNETS
  ########################

  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-public-az1"

  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-public-az2"

  ########################
  # PRIVATE WEB SUBNETS
  ########################

  PrivateWebAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.11.0/24
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-web-az1"

  PrivateWebAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.12.0/24
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-web-az2"

  ########################
  # PRIVATE APP SUBNETS
  ########################

  PrivateAppAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.21.0/24
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-app-az1"

  PrivateAppAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.22.0/24
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-app-az2"

  ########################
  # PRIVATE DB SUBNETS
  ########################

  PrivateDbAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: 10.0.31.0/24
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-db-az1"

  PrivateDbAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: 10.0.32.0/24
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-${Environment}-db-az2"

Outputs:
  VpcId:
    Value:
      Ref: VPC

  PublicSubnets:
    Value:
      Fn::Join:
        - ","
        - - Ref: PublicSubnetAZ1
          - Ref: PublicSubnetAZ2

  PrivateWebSubnets:
    Value:
      Fn::Join:
        - ","
        - - Ref: PrivateWebAZ1
          - Ref: PrivateWebAZ2

  PrivateAppSubnets:
    Value:
      Fn::Join:
        - ","
        - - Ref: PrivateAppAZ1
          - Ref: PrivateAppAZ2

  PrivateDbSubnets:
    Value:
      Fn::Join:
        - ","
        - - Ref: PrivateDbAZ1
          - Ref: PrivateDbAZ2
